// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BossBank.Data.Models
{
    public partial class Colaborador
    {
        public Colaborador()
        {
            ContaCorrente = new HashSet<ContaCorrente>();
            ContaPoupanca = new HashSet<ContaPoupanca>();
        }

        [Key]
        [Column("id_colab")]
        [DisplayName("ID")]
        public int IdColab { get; set; }
        [Required]
        [Column("nome_colab")]
        [StringLength(100)]
        [DisplayName("Nome")]
        public string NomeColab { get; set; }
        [Required]
        [Column("cpf_colab")]
        [StringLength(50)]
        [DisplayName("CPF")]
        public string CpfColab { get; set; }
        [Required]
        [Column("cargo_colab")]
        [StringLength(50)]
        [DisplayName("Função")]
        public string CargoColab { get; set; }
        [Required]
        [Column("salario_colab")]
        [StringLength(100)]
        [DisplayName("Salário")]
        public string SalarioColab { get; set; }

        [InverseProperty("GerenteCcNavigation")]
        public virtual ICollection<ContaCorrente> ContaCorrente { get; set; }
        [InverseProperty("GerenteCpNavigation")]
        public virtual ICollection<ContaPoupanca> ContaPoupanca { get; set; }
    }
}