// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BossBank.Data.Models
{
    public partial class ContaCorrente
    {
        [Key]
        [Column("conta_cc")]
        public int ContaCc { get; set; }
        [Column("agencia_cc")]
        public int AgenciaCc { get; set; }
        [Column("titular_cc")]
        public int TitularCc { get; set; }
        [Column("gerente_cc")]
        public int GerenteCc { get; set; }
        [Required]
        [Column("saldo_cc")]
        [StringLength(100)]
        public string SaldoCc { get; set; }
        [Column("credito_cc")]
        [StringLength(100)]
        public string CreditoCc { get; set; }

        [ForeignKey(nameof(GerenteCc))]
        [InverseProperty(nameof(Colaborador.ContaCorrente))]
        public virtual Colaborador GerenteCcNavigation { get; set; }
        [ForeignKey(nameof(TitularCc))]
        [InverseProperty(nameof(Cliente.ContaCorrente))]
        public virtual Cliente TitularCcNavigation { get; set; }
    }
}