// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BossBank.Data.Models
{
    public partial class ContaPoupanca
    {
        [Key]
        [Column("conta_cp")]
        public int ContaCp { get; set; }
        [Column("agencia_cp")]
        public int AgenciaCp { get; set; }
        [Column("titular_cp")]
        public int TitularCp { get; set; }
        [Column("gerente_cp")]
        public int GerenteCp { get; set; }
        [Required]
        [Column("saldo_cp")]
        [StringLength(100)]
        public string SaldoCp { get; set; }
        [Column("credito_cp")]
        [StringLength(100)]
        public string CreditoCp { get; set; }

        [ForeignKey(nameof(GerenteCp))]
        [InverseProperty(nameof(Colaborador.ContaPoupanca))]
        public virtual Colaborador GerenteCpNavigation { get; set; }
        [ForeignKey(nameof(TitularCp))]
        [InverseProperty(nameof(Cliente.ContaPoupanca))]
        public virtual Cliente TitularCpNavigation { get; set; }
    }
}