// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace BossBank.Data.Models
{
    internal class DisplayNameAttribute : Attribute
    {
        private string v;

        public DisplayNameAttribute(string v)
        {
            this.v = v;
        }
    }
}